<?php

/**
 * Дополнительные объекты недвижимости для демонстрации
 * Больше разнообразных вариантов
 */

return [
    // Больше квартир
    [
        'user_id' => 3,
        'category_id' => 1,
        'title' => '2-комнатная квартира в "Москва-Сити"',
        'slug' => '2k-apartment-moscow-city-luxury',
        'description' => 'Роскошная двухкомнатная квартира с потрясающим видом на деловой центр Москвы. Дизайнерский ремонт, мебель премиум-класса, консьерж-сервис 24/7.',
        'short_description' => 'Luxury квартира 78 кв.м в "Москва-Сити" с панорамным видом',
        'operation_type' => 'rent',
        'price_per_month' => 250000.00,
        'deposit' => 500000.00,
        'currency' => 'RUB',
        'city' => 'Москва',
        'district' => 'Пресненский',
        'street' => 'Пресненская наб.',
        'house_number' => '8с1',
        'apartment' => '4205',
        'full_address' => 'г. Москва, Пресненская наб., д. 8с1, кв. 4205',
        'latitude' => 55.749444,
        'longitude' => 37.538889,
        'property_type' => 'apartment',
        'rooms' => 2,
        'bedrooms' => 1,
        'bathrooms' => 2,
        'area_total' => 78.50,
        'area_living' => 45.00,
        'area_kitchen' => 18.50,
        'floor' => 42,
        'total_floors' => 56,
        'year_built' => 2019,
        'condition_type' => 'excellent',
        'features' => json_encode([
            'panoramic_view' => true,
            'designer_renovation' => true,
            'premium_furniture' => true,
            'concierge' => '24/7',
            'gym' => true,
            'parking' => 'underground',
            'balcony' => 'french_windows'
        ]),
        'status' => 'active',
        'is_featured' => 1,
        'available_from' => date('Y-m-d', strtotime('+1 month')),
        'published_at' => date('Y-m-d H:i:s', strtotime('-2 days'))
    ],
    
    [
        'user_id' => 2,
        'category_id' => 1,
        'title' => 'Студия в центре с евроремонтом',
        'slug' => 'studio-center-euro-renovation',
        'description' => 'Стильная студия после капитального ремонта. Высокие потолки, большие окна, современная техника. В пешей доступности от Красной площади.',
        'short_description' => 'Современная студия 35 кв.м в историческом центре Москвы',
        'operation_type' => 'sale',
        'price' => 8900000.00,
        'currency' => 'RUB',
        'city' => 'Москва',
        'district' => 'Тверской',
        'street' => 'Тверская ул.',
        'house_number' => '15',
        'apartment' => '8',
        'full_address' => 'г. Москва, Тверская ул., д. 15, кв. 8',
        'latitude' => 55.765278,
        'longitude' => 37.605556,
        'property_type' => 'apartment',
        'rooms' => 1,
        'bedrooms' => 1,
        'bathrooms' => 1,
        'area_total' => 35.00,
        'area_living' => 25.00,
        'area_kitchen' => 8.00,
        'floor' => 4,
        'total_floors' => 6,
        'year_built' => 1900,
        'condition_type' => 'excellent',
        'features' => json_encode([
            'high_ceilings' => 3.2,
            'historic_building' => true,
            'euro_renovation' => true,
            'modern_appliances' => true,
            'red_square_walking' => '10 min'
        ]),
        'status' => 'active',
        'published_at' => date('Y-m-d H:i:s', strtotime('-4 hours'))
    ],

    // Дома разного типа
    [
        'user_id' => 2,
        'category_id' => 2,
        'title' => 'Таунхаус в КП "Миллениум Парк"',
        'slug' => 'townhouse-millennium-park',
        'description' => 'Современный таунхаус в закрытом коттеджном поселке премиум-класса. Собственный участок, двухуровневая планировка, гараж на 2 машины.',
        'short_description' => 'Таунхаус 220 кв.м с участком 4 сотки в премиум КП',
        'operation_type' => 'sale',
        'price' => 28500000.00,
        'currency' => 'RUB',
        'city' => 'Одинцово',
        'district' => 'Одинцовский район',
        'street' => 'КП "Миллениум Парк"',
        'house_number' => '47',
        'full_address' => 'Московская обл., Одинцовский р-н, КП "Миллениум Парк", д. 47',
        'latitude' => 55.675000,
        'longitude' => 37.266667,
        'property_type' => 'townhouse',
        'rooms' => 5,
        'bedrooms' => 3,
        'bathrooms' => 3,
        'area_total' => 220.00,
        'area_living' => 140.00,
        'floor' => 2,
        'total_floors' => 2,
        'year_built' => 2022,
        'condition_type' => 'new',
        'features' => json_encode([
            'private_land' => 400,
            'garage' => '2_cars',
            'gated_community' => true,
            'security' => '24/7',
            'playground' => true,
            'lake_nearby' => true,
            'forest_nearby' => true
        ]),
        'status' => 'active',
        'is_featured' => 1,
        'published_at' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],

    [
        'user_id' => 3,
        'category_id' => 2,
        'title' => 'Дача с баней и огородом',
        'slug' => 'dacha-with-banya-garden',
        'description' => 'Уютная дача на участке 12 соток с плодовым садом, огородом и русской баней. Дом деревянный, ухоженный участок, скважина.',
        'short_description' => 'Дача 80 кв.м на участке 12 соток с баней и садом',
        'operation_type' => 'sale',
        'price' => 3200000.00,
        'currency' => 'RUB',
        'city' => 'Сергиев Посад',
        'district' => 'СНТ "Березка"',
        'street' => 'СНТ "Березка"',
        'house_number' => 'уч. 156',
        'full_address' => 'Московская обл., Сергиево-Посадский р-н, СНТ "Березка", уч. 156',
        'latitude' => 56.300000,
        'longitude' => 38.133333,
        'property_type' => 'dacha',
        'rooms' => 3,
        'bedrooms' => 2,
        'bathrooms' => 1,
        'area_total' => 80.00,
        'area_living' => 50.00,
        'year_built' => 1995,
        'condition_type' => 'good',
        'features' => json_encode([
            'garden_area' => 1200,
            'fruit_trees' => true,
            'vegetable_garden' => true,
            'banya' => 'russian',
            'well' => true,
            'electricity' => true,
            'wood_house' => true
        ]),
        'status' => 'active',
        'published_at' => date('Y-m-d H:i:s', strtotime('-3 days'))
    ],

    // Коммерческая недвижимость
    [
        'user_id' => 2,
        'category_id' => 3,
        'title' => 'Готовый ресторан в центре города',
        'slug' => 'ready-restaurant-city-center',
        'description' => 'Полностью оборудованный ресторан на 80 посадочных мест. Современная кухня, система вентиляции, действующая лицензия.',
        'short_description' => 'Готовый ресторан 300 кв.м с оборудованием и лицензией',
        'operation_type' => 'sale',
        'price' => 15000000.00,
        'currency' => 'RUB',
        'city' => 'Москва',
        'district' => 'Хамовники',
        'street' => 'ул. Остоженка',
        'house_number' => '25с1',
        'full_address' => 'г. Москва, ул. Остоженка, д. 25с1',
        'latitude' => 55.742778,
        'longitude' => 37.595556,
        'property_type' => 'restaurant',
        'area_total' => 300.00,
        'floor' => 1,
        'total_floors' => 3,
        'year_built' => 2010,
        'condition_type' => 'excellent',
        'features' => json_encode([
            'seating_capacity' => 80,
            'professional_kitchen' => true,
            'ventilation_system' => true,
            'alcohol_license' => true,
            'parking' => '15_spaces',
            'summer_terrace' => true,
            'equipment_included' => true
        ]),
        'status' => 'active',
        'is_urgent' => 1,
        'published_at' => date('Y-m-d H:i:s', strtotime('-6 hours'))
    ],

    [
        'user_id' => 3,
        'category_id' => 3,
        'title' => 'Торговое помещение в ТЦ',
        'slug' => 'retail-space-shopping-center',
        'description' => 'Торговое помещение на первом этаже популярного ТЦ. Высокая проходимость, отдельный вход с улицы, возможность любого профиля деятельности.',
        'short_description' => 'Магазин 85 кв.м в ТЦ с высокой проходимостью',
        'operation_type' => 'rent',
        'price_per_month' => 180000.00,
        'currency' => 'RUB',
        'city' => 'Москва',
        'district' => 'Северное Бутово',
        'street' => 'ул. Скобелевская',
        'house_number' => '25',
        'full_address' => 'г. Москва, ул. Скобелевская, д. 25, ТЦ "Океан"',
        'latitude' => 55.625000,
        'longitude' => 37.553333,
        'property_type' => 'retail',
        'area_total' => 85.00,
        'floor' => 1,
        'total_floors' => 3,
        'year_built' => 2018,
        'condition_type' => 'new',
        'features' => json_encode([
            'high_traffic' => true,
            'street_entrance' => true,
            'any_business_type' => true,
            'parking' => 'free_for_customers',
            'loading_area' => true,
            'security' => '24/7'
        ]),
        'status' => 'active',
        'available_from' => date('Y-m-d', strtotime('+2 weeks')),
        'published_at' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],

    // Земельные участки
    [
        'user_id' => 2,
        'category_id' => 4,
        'title' => 'Участок 25 соток с лесом и озером',
        'slug' => 'land-25-acres-forest-lake',
        'description' => 'Уникальный участок с выходом к лесу и частному озеру. Идеально подходит для строительства загородной резиденции. Тихое место вдали от городской суеты.',
        'short_description' => 'Эксклюзивный участок 25 соток у леса с приватным озером',
        'operation_type' => 'sale',
        'price' => 12000000.00,
        'currency' => 'RUB',
        'city' => 'Истра',
        'district' => 'Истринский район',
        'street' => 'КП "Лесное озеро"',
        'house_number' => 'уч. 12',
        'full_address' => 'Московская обл., Истринский р-н, КП "Лесное озеро", уч. 12',
        'latitude' => 55.916667,
        'longitude' => 36.850000,
        'property_type' => 'land',
        'area_total' => 2500.00,
        'condition_type' => 'excellent',
        'features' => json_encode([
            'forest_access' => true,
            'private_lake' => true,
            'electricity' => '15kW',
            'gas' => 'natural_pipeline',
            'water' => 'artesian_well',
            'exclusive_location' => true,
            'building_permit' => true
        ]),
        'status' => 'active',
        'is_featured' => 1,
        'published_at' => date('Y-m-d H:i:s', strtotime('-2 days'))
    ]
];